version: '3.9'
services:
  01-host:
    build:
      dockerfile: ./01-host/Dockerfile
    ports:
      - "8080:8080"
    links:
      - 02-mf-navbar
      - 03-counter
      - 04-cards
      - 05-detalle-personaje
  02-mf-navbar:
    build:
      dockerfile: ./02-mf-navbar/Dockerfile
    ports:
      - "8081:8081"
  03-counter:
    build:
      dockerfile: ./03-Counter/Dockerfile
    ports:
      - "8082:8082"
  04-cards:
    build:
      dockerfile: ./04-Cards/Dockerfile
    ports:
      - "8083:8083"
  05-detalle-personaje:
    build:
      dockerfile: ./05-Detalle-Personaje/Dockerfile
    ports:
      - "8084:8084"