version: '3.9'
services:
  host:
    build:
      context: host
      dockerfile: ./host/Dockerfile
    ports:
      - "8080:8080"
    links:
      - mf_navbar
      - mf_counter
      - mf_cards
      - mf_detalle_personaje
  mf_navbar:
    build:
      context: mf_navbar
      dockerfile: ./mf_navbar/Dockerfile
    ports:
      - "8081:8081"
  mf_counter:
    build:
      context: mf_counter
      dockerfile: ./mf_counter/Dockerfile
    ports:
      - "8082:8082"
  mf_cards:
    build:
      context: mf_cards
      dockerfile: ./mf_cards/Dockerfile
    ports:
      - "8083:8083"
  mf_detalle_personaje:
    build:
      context: mf_detalle_personaje
      dockerfile: ./mf_detalle_personaje/Dockerfile
    ports:
      - "8084:8084"